# From IEA dataset
reference_variables:
  IEA Primary Energy:
    ref_year: 2020
    compare_year: 2020
    model: Reference
    scenario: IEA Energy Statistics (r2022)
    key_historical: True
    key_future: False
    variables_threshold:
      Primary Energy: 0.2
      # Primary Energy|Nuclear: 0.4

  # IEA2019 Electricity|Nuclear:
    # ref_year: 2019
    # compare_year: 2019
    # model: Reference
    # scenario: IEA Energy Statistics (r2022)
    # key_historical: False
    # key_future: False
    # variables_threshold:
      # Secondary Energy|Electricity|Nuclear: 0.3

  IEA Electricity:
    ref_year: 2020
    compare_year: 2020
    model: Reference
    scenario: IEA Energy Statistics (r2022)
    key_historical: True
    key_future: False
    variables_threshold:
      Secondary Energy|Electricity: 0.3
      Secondary Energy|Electricity|Nuclear: 0.3
      Secondary Energy|Electricity|Solar-Wind: 0.5
      
# From EDGAR
  # IEA2019 Primary Energy:
    # ref_year: 2019
    # compare_year: 2019
    # model: Reference
    # scenario: IEA Energy Statistics (r2022)
    # key_historical: True
    # key_future: False
    # variables_threshold:
      # Primary Energy: 0.2
      
  EDGAR Emissions|CO2|EIP :
    ref_year: 2019
    compare_year: 2019
    model: Reference
    scenario: EDGAR AR6
    key_historical: True
    key_future: False
    variables_threshold:
      Emissions|CO2|Energy and Industrial Processes: 0.2
      Emissions|CH4: 0.5


aggregation_variables:
  CO2:
    variable: Emissions|CO2
    threshold: 0.2
    key_historical: False
    key_future: False
  CCS:
    variable: Carbon Sequestration|CCS
    threshold: 0.2
    key_historical: False
    key_future: False
  Primary Energy:
    variable: Primary Energy
    threshold: 0.2
    key_historical: False
    key_future: False    


bounds_variables:
    
  Emissions|CO2|Energy and Industrial Processes '10-'20:
    variable: Emissions|CO2|Energy and Industrial Processes|2010-2020 change
    lo: -0.3
    up: 0
    year: 2010
    key_historical: False
    key_future: False
    bound_threshold: 1
    
  Emissions|CO2|Energy '10-'20:
    variable: Emissions|CO2|Energy|2010-2020 change
    lo: -0.3
    up: 0
    year: 2010
    key_historical: True
    key_future: False
    bound_threshold: 1

  CCS from Energy 2020:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: -10
    up: 10
    year: 2020
    key_historical: False
    key_future: False
    bound_threshold: 1 
  Secondary Energy Solar-Wind increase '20-'30:
    variable: Secondary Energy|Electricity|Solar-Wind|2020-2030 change
    lo: -0.2
    up: 300
    year: 2020
    key_historical: False
    key_future: True
    bound_threshold: 1
    
  No net negative before 2030:
    variable: Emissions|CO2|Energy and Industrial Processes
    lo: 0
    up: 10000
    year: 2010-2030
    key_historical: False
    key_future: True
    bound_threshold: 1
    
  No net negative before 2030:
    variable: Emissions|CO2|Energy
    lo: 0
    up: 10000
    year: 2010-2030
    key_historical: False
    key_future: True
    bound_threshold: 1
    
  CCS from Energy 2030:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: 0
    up: 500
    year: 2030
    key_historical: False
    key_future: True
    bound_threshold: 1
    
  Electricity from Nuclear in 2030:
    variable: Secondary Energy|Electricity|Nuclear
    lo: 0
    up: 5
    year: 2030
    key_historical: False
    key_future: True
    bound_threshold: 1
  

