
reference_variables:
  CEDS1:
    ref_year: 2015
    compare_year: 2015
    model: Reference
    scenario: CEDS
    key_historical: True
    key_future: False
    variables_threshold:
      Emissions|CO2: 0.4
      Emissions|CO2|Energy and Industrial Processes: 0.2
      Emissions|CH4: 0.4
  IEA1:
    ref_year: 2015
    compare_year: 2015
    model: Reference
    scenario: IEA Energy Statistics*
    key_historical: True
    key_future: False
    variables_threshold:
      Primary Energy: 0.2
      Secondary Energy|Electricity|Solar-Wind share: 1
      Secondary Energy|Electricity|Solar-Wind: 0.4
      Secondary Energy|Electricity|Nuclear: 0.3

  EDGAR:
    ref_year: 2018
    compare_year: 2020
    model: Reference
    scenario: EDGAR
    key_historical: True
    key_future: False
    variables_threshold:
      Emissions|CO2: 0.4
      Emissions|CO2|Energy and Industrial Processes: 0.2
      Emissions|CH4: 0.4
      #Primary Energy: 0.2
      #Secondary Energy|Electricity|Solar-Wind share: 1
      #Secondary Energy|Electricity|Solar-Wind: 0.4      

  N2O:
    ref_year: 2010
    compare_year: 2010
    model: Reference
    scenario: RCP
    key_historical: False
    key_future: False
    variables_threshold:
      Emissions|N2O: 0.4


aggregation_variables:
  CO2:
    variable: Emissions|CO2
    threshold: 0.2
    key_historical: False
    key_future: False
  CCS:
    variable: Carbon Sequestration|CCS
    threshold: 0.2
    key_historical: False
    key_future: False


bounds_variables:
  Increased renewables 2020-2030:
    variable: Primary Energy|Renewables share|Next decade change
    lo: -0.2
    up: null
    year: 2020
    key_historical: False
    key_future: False
  Increased Solar-Wind 2020-2030:
    variable: Primary Energy|Solar-Wind share|Next decade change
    lo: -0.2
    up: null
    year: 2020
    key_historical: False
    key_future: True
  Increased secondary energy Solar-Wind '20-'30:
    variable: Secondary Energy|Electricity|Solar-Wind share|Next decade change
    lo: -0.2
    up: null
    year: 2020
    key_historical: False
    key_future: True
  No net negative before 2030:
    variable: Emissions|CO2
    lo: 0
    up: null
    year: 2010-2030
    key_historical: False
    key_future: True
  CCS from Energy 2020:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: null
    up: 500
    year: 2020
    key_historical: False
    key_future: False
  CCS from Energy 2030:
    variable: Carbon Sequestration|CCS|Biomass and Fossil
    lo: null
    up: 1000
    year: 2030
    key_historical: False
    key_future: False
  

